#pragma once

#define FASTFETCH_PROJECT_NAME "fastfetch"
#define FASTFETCH_PROJECT_VERSION "2.38.0"
#define FASTFETCH_PROJECT_VERSION_MAJOR 2
#define FASTFETCH_PROJECT_VERSION_MINOR 38
#define FASTFETCH_PROJECT_VERSION_PATCH 0
#define FASTFETCH_PROJECT_VERSION_GIT "2.38.0-9-g6ef4f62d"
#define FASTFETCH_PROJECT_VERSION_TWEAK "-9"
#define FASTFETCH_PROJECT_VERSION_TWEAK_NUM 9
#define FASTFETCH_PROJECT_CMAKE_BUILD_TYPE "RelWithDebInfo"
#define FASTFETCH_PROJECT_HOMEPAGE_URL "https://github.com/fastfetch-cli/fastfetch"
#define FASTFETCH_PROJECT_DESCRIPTION "Fast neofetch-like system information tool"
#define FASTFETCH_PROJECT_LICENSE "MIT license"

#define FASTFETCH_TARGET_DIR_ROOT ""
#define FASTFETCH_TARGET_DIR_USR "/usr"
#define FASTFETCH_TARGET_DIR_HOME "/home"
#define FASTFETCH_TARGET_DIR_ETC "/etc"

#define FASTFETCH_TARGET_DIR_INSTALL_SYSCONF "/etc"
